"""Initial schema

Revision ID: 3cf1c51da32a
Revises: 
Create Date: 2026-02-05 16:10:21.181415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf1c51da32a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractions',
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('blob_name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_tier', sa.String(length=50), nullable=True),
    sa.Column('commodity_type', sa.String(length=50), nullable=True),
    sa.Column('utility_provider', sa.String(length=200), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('extraction_id')
    )
    op.create_index(op.f('ix_extractions_file_hash'), 'extractions', ['file_hash'], unique=False)
    op.create_table('format_fingerprints',
    sa.Column('fingerprint_id', sa.Uuid(), nullable=False),
    sa.Column('utility', sa.String(length=200), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('detection_signals_json', sa.JSON(), nullable=False),
    sa.Column('known_issues', sa.Text(), nullable=True),
    sa.Column('custom_prompt_additions', sa.Text(), nullable=True),
    sa.Column('accuracy_history', sa.JSON(), nullable=False),
    sa.Column('invoices_processed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('fingerprint_id')
    )
    op.create_index(op.f('ix_format_fingerprints_utility'), 'format_fingerprints', ['utility'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.extraction_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_log_extraction_id'), 'audit_log', ['extraction_id'], unique=False)
    op.create_table('corrections',
    sa.Column('correction_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('field_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('correction_type', sa.String(length=50), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('corrector_id', sa.String(length=200), nullable=True),
    sa.Column('invoice_context_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.extraction_id'], ),
    sa.PrimaryKeyConstraint('correction_id')
    )
    op.create_index(op.f('ix_corrections_extraction_id'), 'corrections', ['extraction_id'], unique=False)
    op.create_table('drift_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('extraction_id', sa.Uuid(), nullable=False),
    sa.Column('previous_extraction_id', sa.Uuid(), nullable=False),
    sa.Column('drift_fields_json', sa.JSON(), nullable=False),
    sa.Column('fatal_drift', sa.Boolean(), nullable=False),
    sa.Column('cause_hypothesis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.extraction_id'], ),
    sa.ForeignKeyConstraint(['previous_extraction_id'], ['extractions.extraction_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_drift_events_extraction_id'), 'drift_events', ['extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drift_events_extraction_id'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_index(op.f('ix_corrections_extraction_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_audit_log_extraction_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_format_fingerprints_utility'), table_name='format_fingerprints')
    op.drop_table('format_fingerprints')
    op.drop_index(op.f('ix_extractions_file_hash'), table_name='extractions')
    op.drop_table('extractions')
    # ### end Alembic commands ###
